### PR TITLE
Fix memory leak identified by the address sanitizer.

### LINKED ISSUE #202: Memory error in abl_bndry_output
https://my.cdash.org/test/8724979

### PR DESCRIPTION
**Pull request by marchdf**
Closes #202

### CODE REVIEW

File: amr-wind/wind_energy/ABLBoundaryPlane.cpp [hunk 1]
```diff
@@ -204,10 +204,10 @@ ABLBoundaryPlane::ABLBoundaryPlane(CFDSim& sim)
     pp.get("bndry_file", m_filename);
 
     for (const auto& plane : m_planes) {
-        amrex::Vector<std::string> valid_planes{{"xlo", "ylo"}};
+        amrex::Vector<std::string> valid_planes{"xlo", "ylo"};
 
-        if (std::find(valid_planes.begin(), valid_planes.end(), plane) !=
-            valid_planes.end()) {
+        if (not(std::find(valid_planes.begin(), valid_planes.end(), plane) !=
+                valid_planes.end())) {
```
Comment (sayerhs) [inline amr-wind/wind_energy/ABLBoundaryPlane.cpp:210]:
```suggestion
        if ((std::find(valid_planes.begin(), valid_planes.end(), plane) ==
                valid_planes.end())) {
```
