### PR TITLE
Disable ABL wall function for a zhi BC

### LINKED ISSUE #803: ABL physics wall_model at zhi is using the wrong zref
Currently for the MO-law there seems to be just one zref, which is either input file specified or the first cell height from the bottom. When the wall model option is specified for zhi, it seems to use the same bottom zref at the top too, which is incorrect.

### PR DESCRIPTION
**Pull request by marchdf**
## Summary

Disable the Moeng wall model on zhi.

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- the unit tests
  - [x] on GPU 
  - [x] on CPU 
- the regression tests
  - [x] on GPU 
  - [x] on CPU 

[gpu_tests.txt](https://github.com/Exawind/amr-wind/files/15080534/gpu_tests.txt)
[cpu_tests.txt](https://github.com/Exawind/amr-wind/files/15080535/cpu_tests.txt)

## Additional background

Closes #803

### CODE REVIEW

**Comment by moprak-nrel** [comment]
We may need to disable this for more than just the `moeng` shear stress, anything that uses quantities from  `MOData` will be incorrect at `zhi` since it will be using the quantities computed at `zlo` like: `utau`, `wspd_mean`, etc. I suspect the right fix might be to disable wall models for `zhi` entirely in `ABLWallFunction`. Example in the `Schumann` wall model: https://github.com/Exawind/amr-wind/blob/38dfd817bace4e6d864d9c0b97ab01e9ff2b7e47/amr-wind/wind_energy/ShearStress.H#L92-L103

File: amr-wind/wind_energy/ABLWallFunction.cpp [hunk 1]
```diff
@@ -170,11 +170,18 @@ void ABLVelWallFunc::wall_model(
...
-    if ((velocity.bc_type()[zlo] != BC::wall_model) &&
-        (velocity.bc_type()[zhi] != BC::wall_model)) {
+    if (velocity.bc_type()[zhi] == BC::wall_model) {
+        amrex::Abort("ABL wall models are not applicable to a zhi BC");
+    }
+    if (velocity.bc_type()[zlo] != BC::wall_model) {
         return;
     }
 
+    if ((velocity.bc_type()[zhi] == BC::wall_model) &&
```
Comment (moprak-nrel) [inline amr-wind/wind_energy/ABLWallFunction.cpp:180]: this branch is not needed anymore since there's a more general `Abort` above

**Review by moprak-nrel — CHANGES_REQUESTED** [review]

File: amr-wind/wind_energy/ABLWallFunction.cpp (hunk 1 above)
Comment (marchdf) [reply amr-wind/wind_energy/ABLWallFunction.cpp]: good catch

**Review by moprak-nrel — APPROVED** [review]
